### ISSUE TITLE
Click on a food option to choose it

### ISSUE THREAD

**Issue by richchurcher** [nikau-2018/lunchbunch#53]
Depends on #52 

Clicking on a food option should choose it for that section of the lunchbox. You'll need:
 - the PUT route for the `/lunchboxes/:id` API endpoint to update our lunchbox with the new choice
 - an async action to send the request and handle the response

**Comment by james-built** [comment]
Do we need to pass in multiple params here? We are trying to pass foodId & lunchboxId
